# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sheetmonkey-server

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: beta
  region: us-west-2
  versionFunctions: false

  environment:
    SS_CLIENT_ID: ${file(data/private/ss-oauth.json):clientID}
    SS_CLIENT_SECRET: ${file(data/private/ss-oauth.json):secret}
    DDB_USERS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-users

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DDB_USERS_TABLE}"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DDB_USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  echo:
    handler: handler.echo
    events:
      - http:
          path: api/echo
          method: get

  ping:
    handler: handler.ping
    events:
      - http:
          path: api/ping
          method: get
  
  jwt:
    handler: handler.jwt #NOTE: don't add an http event to this! This is just for testing locally.
  
  env:
    handler: handler.env #NOTE: don't add an http event to this! This is just for testing locally.

  oauthcodecatcher:
    handler: handler.handleOAuthRedirect
    events:
      - http:
          path: api/oauth/codecatcher
          method: get

  defaultredir:
    handler: handler.defaultredirect
    events:
      - http:
          path: /
          method: get

  indexhtml:
    handler: handler.staticfile
    events:
      - http:
          path: index.html
          method: get
  
  bootstrapcss:
    handler: handler.staticfile
    events:
      - http:
          path: bootstrap.min.css
          method: get
  
  bootstrapjs:
    handler: handler.staticfile
    events:
      - http:
          path: bootstrap.min.js
          method: get

  indexdistjs:
    handler: handler.staticfile
    events:
      - http:
          path: index_dist.js
          method: get

  indexjs:
    handler: handler.staticfile
    events:
      - http:
          path: index.js
          method: get

  jquery:
    handler: handler.staticfile
    events:
      - http:
          path: jquery.min.js
          method: get

  stylecss:
    handler: handler.staticfile
    events:
      - http:
          path: style.css
          method: get

  sveltecss:
    handler: handler.staticfile
    events:
      - http:
          path: svelte.css
          method: get